### ISSUE TITLE
4th column stays blanc

### ISSUE THREAD

**Issue by blumenkraft** [33mhz/broadsword-issues#22]
4th column stays blanc
<img width="1678" alt="screenshot 2015-07-31 14 47 45" src="https://cloud.githubusercontent.com/assets/4653850/9007600/26fe2306-3793-11e5-920b-1fba4ee3f569.png">

**Comment by 33mhz** [comment]
Please include what browser you're using and your screen resolution.

**Comment by blumenkraft** [comment]
Resolution: 2880 x 1800 Retina
Browser:          Safari, Chrome, Firefox

i will test a bug on every of the 3 mentioned browser before i submit them. if a bug appears in only one of those browsers i'll mention it. i think this way it is easier for us both, don't you think so too?

**Comment by 33mhz** [comment]
Bug reports are better with all info, so anyone can tell what's being talked about and try to reproduce. But it's not a big deal.

I can see that the columns are spaced widely enough that there isn't space for a fourth column. But I'm not sure why that is. I'll take a look at the calculations.

**Comment by blumenkraft** [comment]
Don't know if related, but since you mentioned column spacing i thought i should mention it. In two and three column mode there is a whitespace on the right. 

<img width="414" alt="screenshot 2015-07-31 16 11 17" src="https://cloud.githubusercontent.com/assets/4653850/9009061/e5412150-379e-11e5-8f2b-50cb85a5f17e.png">

**Comment by 33mhz** [comment]
@blumenkraft It should be better after a refresh. Let me know if it's doing any better.

**Comment by blumenkraft** [comment]
Sorry to say, still blank for me. :-/

**Comment by 33mhz** [comment]
Still true?

**Comment by 33mhz** [comment]
Closing for age.
