### ISSUE TITLE
Add posting using 'Enter'

### ISSUE THREAD

**Issue by blumenkraft** [33mhz/broadsword-issues#24]
Enter = cmd+return
Hint: KeyCode: 13 on Mac

**Comment by 33mhz** [comment]
Works on Firefox, Chrome, and Opera in Windows. The code is currently `e.which == 13 && (e.ctrlKey || e.metaKey)`. Will try a few things out.

**Comment by 33mhz** [comment]
Is this still true?

* It doesn't work for replies, just the primary post.

**Comment by 33mhz** [comment]
Closing for age.
