### ISSUE TITLE
Buttons hidden [Screenshot]

### ISSUE THREAD

**Issue by blumenkraft** [33mhz/broadsword-issues#25]
This is only in Firefox for me. In Chrome and Safari the buttons are not hidden. (Retina display)

<img width="1304" alt="screenshot 2015-07-31 15 11 05" src="https://cloud.githubusercontent.com/assets/4653850/9007943/76a94c0c-3796-11e5-84b2-432857330e79.png">

**Comment by 33mhz** [comment]
Probably to do with the font size. I'll take a look. Should be able to fix fairly easily.

**Comment by 33mhz** [comment]
@blumenkraft Let me know if this is improved after a refresh.

**Comment by blumenkraft** [comment]
Yes, issue solved! :) -closed-
