### ISSUE TITLE
Reload makes all column states disappear. Welcome page shows up.

### ISSUE THREAD

**Issue by blumenkraft** [33mhz/broadsword-issues#26]
Every time i reload the site or i click a link and go back it shows up with the welcome screen so i need to click all the column buttons on and on again. It would be great if it could remember the state of the last visit column wise.

**Comment by 33mhz** [comment]
Sounds good to me. I can save that in localstorage, likely.

**Comment by blumenkraft** [comment]
Nice! Thank you :)

**Comment by 33mhz** [comment]
Done! Some edge cases. I think searches won't come back up.
