### ISSUE TITLE
Private message multi-send bug!

### ISSUE THREAD

**Issue by blumenkraft** [33mhz/broadsword-issues#27]
It is possible to send the same message several times if you only hit the button fast enough.
By accident it happened to me twice now (double send in this cases).

I've seen other clients provide a protection against that.

<img width="470" alt="screenshot 2015-08-11 16 15 19" src="https://cloud.githubusercontent.com/assets/4653850/9199743/7aff3544-4044-11e5-8cc0-a4cb7e33259f.png">

**Comment by 33mhz** [comment]
This will have to wait until I swap over to a different build of Broadsword. I'm doing it wrong.

**Comment by blumenkraft** [comment]
No hurry! :dancer:

**Comment by 33mhz** [comment]
This is fixed in the next version, which is waiting for... photo uploading to work. :/

**Comment by 33mhz** [comment]
Done.
