### ISSUE TITLE
Scroll bar hides button.

### ISSUE THREAD

**Issue by blumenkraft** [33mhz/broadsword-issues#28]
This is for Safari on Mac (Retina Display). If scroll bar is displayed the button (screenshot) is kind of hidden. the few pixel left are very hard to hit. May i suggest bigger buttons.

<img width="157" alt="screenshot 2015-08-11 19 16 26" src="https://cloud.githubusercontent.com/assets/4653850/9204444/9c0da806-405d-11e5-88b8-6bb1d895c7c8.png">

**Comment by blumenkraft** [comment]
Correction: This is also in Firefox and Chrome

<img width="733" alt="screenshot 2015-08-12 13 59 54" src="https://cloud.githubusercontent.com/assets/4653850/9223470/a4a65218-40fa-11e5-9b8d-1f68124b3f42.png">

**Comment by 33mhz** [comment]
Wonder if this is still true?

**Comment by 33mhz** [comment]
Closing for age.
