### ISSUE TITLE
Gut and open source for pnut.io

### ISSUE THREAD

**Issue by 33mhz** [33mhz/broadsword-issues#31]

**Comment by cdn** [comment]
References to threads pull ADN threads up in treeview!?

Smaller screens would benefit from;
<meta name="viewport" content="width=device-width, target-densitydpi=160dpi, initial-scale=1">

And bigger buttons…

**Comment by 33mhz** [comment]
Those issues are more solved. Need to go through and resize pretty much everything. Silly thing makes itself bigger than my screen, on mobile.

**Comment by blumenkraft** [comment]
Responsive is a bitch!
