### ISSUE TITLE
enable/disable or otherwise configure keybindings

### ISSUE THREAD

**Issue by spacenerdmo** [33mhz/broadsword-issues#41]
Default keybindings in broadsword can overlap with common keybindings used by the browser and on occasion a desktop window manager resulting in undesired behavior.  The ability to at least disable or otherwise configure what those key bindings are would be helpful.

Example:  CTRL+N to open a new window in Firefox and also opens the new post dialog in broadsword.

**Comment by 33mhz** [comment]
For now, I've added just two simple options: on/off for "top navigation", and "everything else", separately. Notably, keyboard shortcuts for sending a post or reply, `Ctrl+Enter`, are always enabled...
